apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-queue-sa
  namespace: task-queue
  labels:
    app: task-queue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: task-queue-role
  namespace: task-queue
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-queue-rolebinding
  namespace: task-queue
subjects:
- kind: ServiceAccount
  name: task-queue-sa
  namespace: task-queue
roleRef:
  kind: Role
  name: task-queue-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: task-queue-netpol
  namespace: task-queue
spec:
  podSelector:
    matchLabels:
      app: task-queue
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app: task-queue
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 3001
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app: task-queue
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 3001
  - to:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9090

